[package]
name = "Rust"
version = "0.1.0"
authors = ["William AbouSharaf <liams_1998@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
